version: '3.8'

services:
  app:
    build: .
    container_name: wow-fansite-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped